remote_theme: /ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Endangered Organisms Tracker"
description: "GPS tracker for Endangered Organisms plants and animals"
author:
  name: "Ramona Hidalgo"

# Do not change the following line.
  copyright: true


theme: jekyll-theme-architect